rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
  #- rbx-19mode

env:
  - RAILS_VERSION=3.1.3
  - RAILS_VERSION=3.2.1
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION=master

matrix:
  exclude:
    - rvm: 1.9.2
      env: RAILS_VERSION=master
